name: Frontend-Artwork-CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests- Using NodeJS ${{ matrix.node-version }}
        run: |
          npm ci
          npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run:
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{
          secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t front .
      - name: Tags
        run: |
          docker tag front ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker tag front ${{ secrets.DOCKER_USER }}/front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/front:latest
